# Generated by Django 5.1.7 on 2025-03-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_current_latitude_trip_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
