# Generated by Django 5.1.7 on 2025-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_logentry_legal_warning_logentry_remaining_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='legal_warning',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='remaining_hours',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='logentry',
            unique_together={('trip', 'date')},
        ),
    ]
